import colorPalette from './img/colorPalette.png';
import superTeam from './img/GLP1-super-team.png';
import goItJs07 from './img/goit-js-hw-07.png';
import goItJs08 from './img/goit-js-hw-08.png';
import goItJs09 from './img/goit-js-hw-09.png';
import goItJs10 from './img/goit-js-hw-10.png';
import goItJs11 from './img/goit-js-hw-11.png';
import goItJs12 from './img/goit-js-hw-12.png';
import goItJs12v2 from './img/goit-js-hw-12v2.png';
import goItMarkup6 from './img/goit-markup-hw-06.png';
import registrationForm from './img/registration-form.png';
import fadeSliderSwiper from './img/slider-fadeEffect-Vite.png';
import sliderSwiper from './img/slider-swiper-Vite.png';
import foodSta from './img/SLP_FoodSta.png';
import hydra from './img/SLP-Hydra.png';
import testForm1 from './img/SP_test-form-1.png';
import ball from './img/sp-ball.png';
import blueCollar from './img/SP-BlueCollar-Vite.png';
import cardForm from './img/sp-card-form.png';
import searchVideoPixabay from './img/sp-SearchVideoPixabay-vite.png';
import timeAndQuestion from './img/sp-TimeQuestion-vite.png';
import hmCandler from './img/SPL_HM-Candler.png';
import homeOfTheBestFood from './img/SPL_home-of-the-best-food.png';
import tea from './img/SPL_tea.png';
import textHidden from './img/text-hidden.png';
import themeBlackWhite from './img/ThemeBlackWhite.png';
import ticTacToe from './img/tic-tac-toe.png';
import mechanicalWatch from './img/time-info.png';


export const projectArr = [
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'colorPalette',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Color Palette',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: colorPalette,
		imgGallery: colorPalette,
		alt: 'Color Palette',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/colorPalette',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/colorPalette/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber: 0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'GLP1-super-team',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Watch Charm',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Group',
		status:true,
		imgPreview: superTeam,
		imgGallery: superTeam,
		alt: 'Watch Charm',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/GLP1-super-team',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/GLP1-super-team/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber: 0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-js-hw-07',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItJs07,
		imgGallery: goItJs07,
		alt: '',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-07',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-07/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:'',
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-js-hw-08',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Gallery basicLightBox',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItJs08,
		imgGallery: goItJs08,
		alt: 'Gallery basicLightBox',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-08',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-08/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber: 0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-js-hw-09',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Gallery simpleLightBox and Form',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItJs09,
		imgGallery: goItJs09,
		alt: 'Gallery simpleLightBox and Form',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-09',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-09/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-js-hw-10',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Timer and Snackbar',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItJs10,
		imgGallery: goItJs10,
		alt: 'Timer and Snackbar',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-10',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-10/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-js-hw-11',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Simple search',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItJs11,
		imgGallery: goItJs11,
		alt: 'Simple search',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-11',
		siteText: 'Site: ',
		siteLink: 'https:// denyshv1.github.io/goit-js-hw-11/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-js-hw-12',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Search with pagination version 1',
		categoryText: 'Category: ',
		category: 'JS Projects',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItJs12,
		imgGallery: goItJs12,
		alt: 'Search with pagination version 1',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-12',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-12/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-js-hw-12v2',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Search with pagination version 2',
		categoryText: 'Category: ',
		category: 'JS Projects',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItJs12v2,
		imgGallery: goItJs12v2,
		alt: 'Search with pagination version 2',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-12v2',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-12v2/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'goit-markup-hw-06',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Web Studio',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: goItMarkup6,
		imgGallery: goItMarkup6,
		alt: 'Web Studio',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/goit-markup-hw-06',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/goit-markup-hw-06/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: '',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'registration-form',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Registration Form',
		categoryText: 'Category: ',
		category: 'Forms',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: registrationForm,
		imgGallery: registrationForm,
		alt: 'Registration Form',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/registration-form',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/registration-form/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'slider-fadeEffect-Vite',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Swiper Fade Version 1',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: fadeSliderSwiper,
		imgGallery: fadeSliderSwiper,
		alt: 'Swiper Fade Version 1',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/slider-fadeEffect-Vite',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/slider-fadeEffect-Vite/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'slider-swiper-Vite',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Swiper Version 2',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: sliderSwiper,
		imgGallery: sliderSwiper,
		alt: 'Swiper Version 2',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/slider-swiper-Vite',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/slider-swiper-Vite/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'SLP_FoodSta',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Food Delivery',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: foodSta,
		imgGallery: foodSta,
		alt: 'Food Delivery',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/SLP_FoodSta',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/SLP_FoodSta/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: '',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'SLP-Hydra',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Hydra',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: hydra,
		imgGallery: hydra,
		alt: 'Hydra',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/SLP-Hydra',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/SLP-Hydra/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: '',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'SP_test-form-1',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'My first form',
		categoryText: 'Category: ',
		category: 'Forms',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: testForm1,
		imgGallery: testForm1,
		alt: 'My first form',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/SP_test-form-1',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/SP_test-form-1/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'sp-ball',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Space Ball',
		categoryText: 'Category: ',
		category: 'Games',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: ball,
		imgGallery: ball,
		alt: 'Space Ball',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/sp-ball',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/sp-ball/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'SP-BlueCollar-Vite',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Blue Collar',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: blueCollar,
		imgGallery: blueCollar,
		alt: 'Blue Collar',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/SP-BlueCollar-Vite',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/SP-BlueCollar-Vite/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'sp-card-form',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Payment Form',
		categoryText: 'Category: ',
		category: 'Forms',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: cardForm,
		imgGallery: cardForm,
		alt: 'Payment Form',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/sp-card-form',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/sp-card-form/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'sp-SearchVideoPixabay-vite',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Simple video search',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: searchVideoPixabay,
		imgGallery: searchVideoPixabay,
		alt: 'Simple video search',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/sp-SearchVideoPixabay-vite',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/sp-SearchVideoPixabay-vite/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'sp-TimeQuestion-vite',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Timers and Questions',
		categoryText: 'Category: ',
		category: 'Games',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: timeAndQuestion,
		imgGallery: timeAndQuestion,
		alt: 'Timers and Questions',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/sp-TimeQuestion-vite',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/sp-TimeQuestion-vite/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'SPL_HM-Candler',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'HM Candler',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: hmCandler,
		imgGallery: hmCandler,
		alt: 'HM Candler',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/SPL_HM-Candler',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/SPL_HM-Candler/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: '',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'SPL_home-of-the-best-food',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'My first WebSide "Home of the best food"',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: homeOfTheBestFood,
		imgGallery: homeOfTheBestFood,
		alt: 'My first WebSide "Home of the best food',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/SPL_home-of-the-best-food',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/SPL_home-of-the-best-food/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: '',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:1,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'SPL_tea',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Tea',
		categoryText: 'Category: ',
		category: 'Web Sides',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: tea,
		imgGallery: tea,
		alt: 'Tea',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/SPL_tea',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/SPL_tea/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: '',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:2,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'text-hidden',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Text Hidden',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: textHidden,
		imgGallery: textHidden,
		alt: 'Text Hidden',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/text-hidden',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/text-hidden/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'ThemeBlackWhite',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Black and White theme',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: themeBlackWhite,
		imgGallery: themeBlackWhite,
		alt: 'Black and White theme',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/ThemeBlackWhite',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/ThemeBlackWhite/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'tic-tac-toe',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Tic Tac Toe',
		categoryText: 'Category: ',
		category: 'Games',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: ticTacToe,
		imgGallery: ticTacToe,
		alt: 'Tic Tac Toe',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/tic-tac-toe',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/tic-tac-toe/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:3,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'time-info',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'Clocks',
		categoryText: 'Category: ',
		category: 'JS Features',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:true,
		imgPreview: mechanicalWatch,
		imgGallery: mechanicalWatch,
		alt: 'Clocks',
		codeLinkText: 'Code: ',
		codeLink: 'https://github.com/DenysHV1/time-info',
		siteText: 'Site: ',
		siteLink: 'https://denyshv1.github.io/time-info/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:0,
	},
	{
		nameOfProjectGitText:'Git name of project: ',
		nameOfProjectGit:'',
		nameOFProjectPreviewText:'Name of project: ',
		nameOFProjectPreview:'',
		categoryText: 'Category: ',
		category: 'Web Side',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status:false,
		imgPreview: '',
		imgGallery: '',
		alt: '',
		codeLinkText: 'Code: ',
		codeLink: '',
		siteText: 'Site: ',
		siteLink: '',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: 'Description',
		description: '',
		projectNumTExt: 'Project number: ',
		ProjectNumber:'',
	},

]