import colorPalette from './img/colorPalette.png';
import superTeam from './img/GLP1-super-team.png';
import goItJs07 from './img/goit-js-hw-07.png';
import goItJs08 from './img/goit-js-hw-08.png';
import goItJs09 from './img/goit-js-hw-09.png';
import goItJs10 from './img/goit-js-hw-10.png';
import goItJs11 from './img/goit-js-hw-11.png';
import goItJs12 from './img/goit-js-hw-12.png';
import goItJs12v2 from './img/goit-js-hw-12v2.png';
import goItMarkup6 from './img/goit-markup-hw-06.png';
import registrationForm from './img/registration-form.png';
import fadeSliderSwiper from './img/slider-fadeEffect-Vite.png';
import sliderSwiper from './img/slider-swiper-Vite.png';
import foodSta from './img/SLP_FoodSta.png';
import hydra from './img/SLP-Hydra.png';
import testForm1 from './img/SP_test-form-1.png';
import ball from './img/sp-ball.png';
import blueCollar from './img/SP-BlueCollar-Vite.png';
import cardForm from './img/sp-card-form.png';
import searchVideoPixabay from './img/sp-SearchVideoPixabay-vite.png';
import timeAndQuestion from './img/sp-TimeQuestion-vite.png';
import hmCandler from './img/SPL_HM-Candler.png';
import homeOfTheBestFood from './img/SPL_home-of-the-best-food.png';
import tea from './img/SPL_tea.png';
import textHidden from './img/text-hidden.png';
import themeBlackWhite from './img/ThemeBlackWhite.png';
import ticTacToe from './img/tic-tac-toe.png';
import mechanicalWatch from './img/time-info.png';
import userProfileElements from './img/user-profile-elements.png';
import reactEvtElements from './img/onClick-evt.png';
import reactTodoList from './img/React/todoList-react.png'
import reactPixabay from './img/React/pixabay-react.png'

export const projectArr = [
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'colorPalette',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Color Palette',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: colorPalette,
		imgGallery: colorPalette,
		alt: 'Color Palette',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/colorPalette',
		siteText: 'Site ',
		siteLink: 'https://denyshv1.github.io/colorPalette/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 2,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'GLP1-super-team',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Watch Charm',
		categoryText: 'Category:',
		category: 'html css main',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Group',
		status: true,
		imgPreview: superTeam,
		imgGallery: superTeam,
		alt: 'Watch Charm',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/GLP1-super-team',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/GLP1-super-team/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 7,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-js-hw-07',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Mix Features',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItJs07,
		imgGallery: goItJs07,
		alt: 'Mix Features',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-07',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-07/',
		technologyText: 'Technology: ',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 1,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-js-hw-08',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Gallery basicLightBox',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItJs08,
		imgGallery: goItJs08,
		alt: 'Gallery basicLightBox',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-08',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-08/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 3,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-js-hw-09',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Gallery simpleLightBox and Form',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItJs09,
		imgGallery: goItJs09,
		alt: 'Gallery simpleLightBox and Form',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-09',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-09/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 6,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-js-hw-10',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Timer and Snackbar',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItJs10,
		imgGallery: goItJs10,
		alt: 'Timer and Snackbar',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-10',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-10/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 9,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-js-hw-11',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Simple search',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItJs11,
		imgGallery: goItJs11,
		alt: 'Simple search',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-11',
		siteText: 'Site',
		siteLink: 'https:// denyshv1.github.io/goit-js-hw-11/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 11,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-js-hw-12',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Search with pagination version 1',
		categoryText: 'Category: ',
		category: 'JS main',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItJs12,
		imgGallery: goItJs12,
		alt: 'Search with pagination version 1',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-12',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-12/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 1,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-js-hw-12v2',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Search with pagination version 2',
		categoryText: 'Category:',
		category: 'JS main',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItJs12v2,
		imgGallery: goItJs12v2,
		alt: 'Search with pagination version 2',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-js-hw-12v2',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/goit-js-hw-12v2/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 2,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'goit-markup-hw-06',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Web Studio',
		categoryText: 'Category:',
		category: 'html css main',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: goItMarkup6,
		imgGallery: goItMarkup6,
		alt: 'Web Studio',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/goit-markup-hw-06',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/goit-markup-hw-06/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: '',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 6,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'registration-form',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Registration Form',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: registrationForm,
		imgGallery: registrationForm,
		alt: 'Registration Form',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/registration-form',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/registration-form/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 3,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'slider-fadeEffect-Vite',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Swiper Fade Version 1',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: fadeSliderSwiper,
		imgGallery: fadeSliderSwiper,
		alt: 'Swiper Fade Version 1',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/slider-fadeEffect-Vite',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/slider-fadeEffect-Vite/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 7,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'slider-swiper-Vite',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Swiper Version 2',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: sliderSwiper,
		imgGallery: sliderSwiper,
		alt: 'Swiper Version 2',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/slider-swiper-Vite',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/slider-swiper-Vite/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 8,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'SLP_FoodSta',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Food Delivery',
		categoryText: 'Category:',
		category: 'html css another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: foodSta,
		imgGallery: foodSta,
		alt: 'Food Delivery',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/SLP_FoodSta',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/SLP_FoodSta/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: '',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 5,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'SLP-Hydra',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Hydra',
		categoryText: 'Category:',
		category: 'html css another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: hydra,
		imgGallery: hydra,
		alt: 'Hydra',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/SLP-Hydra',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/SLP-Hydra/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: '',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 3,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'SP_test-form-1',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'My first form',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: testForm1,
		imgGallery: testForm1,
		alt: 'My first form',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/SP_test-form-1',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/SP_test-form-1/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 1,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'sp-ball',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Space Ball',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: ball,
		imgGallery: ball,
		alt: 'Space Ball',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/sp-ball',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/sp-ball/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 1,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'SP-BlueCollar-Vite',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Blue Collar',
		categoryText: 'Category:',
		category: 'html css main',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: blueCollar,
		imgGallery: blueCollar,
		alt: 'Blue Collar',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/SP-BlueCollar-Vite',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/SP-BlueCollar-Vite/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 8,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'sp-card-form',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Payment Form',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: cardForm,
		imgGallery: cardForm,
		alt: 'Payment Form',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/sp-card-form',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/sp-card-form/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 2,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'sp-SearchVideoPixabay-vite',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Simple video search',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: searchVideoPixabay,
		imgGallery: searchVideoPixabay,
		alt: 'Simple video search',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/sp-SearchVideoPixabay-vite',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/sp-SearchVideoPixabay-vite/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 12,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'sp-TimeQuestion-vite',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Timers and Questions',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: timeAndQuestion,
		imgGallery: timeAndQuestion,
		alt: 'Timers and Questions',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/sp-TimeQuestion-vite',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/sp-TimeQuestion-vite/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 2,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'SPL_HM-Candler',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'HM Candler',
		categoryText: 'Category:',
		category: 'html css another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: hmCandler,
		imgGallery: hmCandler,
		alt: 'HM Candler',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/SPL_HM-Candler',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/SPL_HM-Candler/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: '',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 4,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'SPL_home-of-the-best-food',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'My first WebSide "Home of the best food"',
		categoryText: 'Category:',
		category: 'html css another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: homeOfTheBestFood,
		imgGallery: homeOfTheBestFood,
		alt: 'My first WebSide "Home of the best food',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/SPL_home-of-the-best-food',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/SPL_home-of-the-best-food/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: '',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 1,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'SPL_tea',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Tea',
		categoryText: 'Category: ',
		category: 'html css another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: tea,
		imgGallery: tea,
		alt: 'Tea',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/SPL_tea',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/SPL_tea/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: '',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 2,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'text-hidden',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Text Hidden',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: textHidden,
		imgGallery: textHidden,
		alt: 'Text Hidden',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/text-hidden',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/text-hidden/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 4,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'ThemeBlackWhite',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Black and White theme',
		categoryText: 'Category:',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: themeBlackWhite,
		imgGallery: themeBlackWhite,
		alt: 'Black and White theme',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/ThemeBlackWhite',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/ThemeBlackWhite/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 5,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'tic-tac-toe',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Tic Tac Toe',
		categoryText: 'Category:',
		category: 'JS main',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: ticTacToe,
		imgGallery: ticTacToe,
		alt: 'Tic Tac Toe',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/tic-tac-toe',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/tic-tac-toe/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 3,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'time-info',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Clocks',
		categoryText: 'Category: ',
		category: 'JS another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: mechanicalWatch,
		imgGallery: mechanicalWatch,
		alt: 'Clocks',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/time-info',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/time-info/',
		technologyText: 'Technology:',
		technology1: 'html+css',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 10,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'user-profile-elements-react',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'User Elements',
		categoryText: 'Category:',
		category: 'React another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: userProfileElements,
		imgGallery: userProfileElements,
		alt: 'User Elements',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/user-profile-elements-react',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/user-profile-elements-react/',
		technologyText: 'Technology:',
		technology1: 'React.js',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 1,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'onClick-events-react',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'User Event onClick Elements',
		categoryText: 'Category:',
		category: 'React another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: reactEvtElements,
		imgGallery: reactEvtElements,
		alt: 'User event Elements',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/onClick-events-react',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/onClick-events-react/',
		technologyText: 'Technology:',
		technology1: 'React.js',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 2,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'todoList-react',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'To do list',
		categoryText: 'Category:',
		category: 'React main',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: reactTodoList,
		imgGallery: reactTodoList,
		alt: 'To do list',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/todoList-react',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/todoList-react/',
		technologyText: 'Technology:',
		technology1: 'React.js',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 3,
	},
	{
		nameOfProjectGitText: 'Git name:',
		nameOfProjectGit: 'http-react',
		nameOFProjectPreviewText: 'Name:',
		nameOFProjectPreview: 'Pixabay search',
		categoryText: 'Category:',
		category: 'React another',
		typeOfProjectText: 'Type of project',
		typeOfProject: 'Solo',
		status: true,
		imgPreview: reactPixabay,
		imgGallery: reactPixabay,
		alt: 'Pixabay search',
		codeLinkText: 'Code',
		codeLink: 'https://github.com/DenysHV1/http-react',
		siteText: 'Site',
		siteLink: 'https://denyshv1.github.io/http-react/',
		technologyText: 'Technology:',
		technology1: 'React.js',
		technology2: 'JavaScript',
		descriptionText: '',
		description: '',
		projectNumTExt: 'Project number:',
		ProjectNumber: 3,
	},
];
